#!/usr/bin/env bash
set -u
set -o pipefail

# AWS Small Server Readiness Toolkit
# Ubuntu Server Audit Script
#
# Purpose:
#   Generate a read-only Markdown report for a small Ubuntu server.
#
# Safety:
#   This script does not modify system configuration.
#   It does not install packages, restart services, change firewall rules,
#   or create AWS resources.
#
# Usage:
#   ./scripts/ubuntu-server-audit.sh
#   sudo ./scripts/ubuntu-server-audit.sh   # optional, gives more complete output

PROJECT_NAME="AWS Small Server Readiness Toolkit"
SCRIPT_NAME="ubuntu-server-audit.sh"
TIMESTAMP="$(date '+%Y%m%d-%H%M%S')"
REPORT_DIR="reports"
REPORT_FILE="${REPORT_DIR}/ubuntu-server-audit-${TIMESTAMP}.md"

mkdir -p "${REPORT_DIR}"

run_cmd() {
  local title="$1"
  shift

  {
    echo
    echo "### ${title}"
    echo
    echo '```text'
    "$@" 2>&1 || true
    echo '```'
  } >> "${REPORT_FILE}"
}

run_shell() {
  local title="$1"
  local command="$2"

  {
    echo
    echo "### ${title}"
    echo
    echo '```text'
    bash -c "${command}" 2>&1 || true
    echo '```'
  } >> "${REPORT_FILE}"
}

section() {
  {
    echo
    echo "## $1"
  } >> "${REPORT_FILE}"
}

write_header() {
  cat > "${REPORT_FILE}" <<EOF
# Ubuntu Server Audit Report

Generated by: ${PROJECT_NAME} / ${SCRIPT_NAME}

Generated at: $(date '+%Y-%m-%d %H:%M:%S %Z')

> This report is generated by a read-only audit script. It is intended for practical server readiness review and documentation. It is not a legal compliance report, penetration test, or security certification.

EOF
}

check_command_exists() {
  local cmd="$1"

  if command -v "${cmd}" >/dev/null 2>&1; then
    echo "available"
  else
    echo "not found"
  fi
}

write_summary_findings() {
  {
    echo
    echo "## Quick Summary"
    echo
    echo "| Item | Result |"
    echo "|---|---|"
    echo "| Hostname | $(hostname 2>/dev/null || echo 'unknown') |"
    echo "| OS | $(. /etc/os-release 2>/dev/null && echo "${PRETTY_NAME:-unknown}" || echo 'unknown') |"
    echo "| Kernel | $(uname -r 2>/dev/null || echo 'unknown') |"
    echo "| Current user | $(whoami 2>/dev/null || echo 'unknown') |"
    echo "| Sudo/root execution | $([ "$(id -u)" -eq 0 ] && echo 'yes' || echo 'no') |"
    echo "| Docker command | $(check_command_exists docker) |"
    echo "| UFW command | $(check_command_exists ufw) |"
    echo "| AWS CLI command | $(check_command_exists aws) |"
    echo "| curl command | $(check_command_exists curl) |"
    echo "| ss command | $(check_command_exists ss) |"
  } >> "${REPORT_FILE}"
}

write_manual_review_notes() {
  cat >> "${REPORT_FILE}" <<'EOF'

## Manual Review Notes

Use this section to record human review findings.

### Access Control

- [ ] Confirm who has SSH access.
- [ ] Confirm whether password-based SSH login is disabled.
- [ ] Confirm whether root SSH login is disabled.
- [ ] Confirm whether access is restricted by source IP or VPN.
- [ ] Confirm whether AWS Systems Manager Session Manager is used.

### AWS / EC2

- [ ] Confirm this server is running in the intended AWS region.
- [ ] Confirm the instance type is appropriate.
- [ ] Confirm EBS volumes are encrypted.
- [ ] Confirm Security Groups expose only required ports.
- [ ] Confirm public IP usage is intentional.
- [ ] Confirm IAM role permissions are minimal.

### Backup and Restore

- [ ] Confirm whether EBS snapshots are configured.
- [ ] Confirm whether application data is backed up.
- [ ] Confirm whether database backup exists.
- [ ] Confirm whether restore testing has been performed.
- [ ] Confirm retention period and backup owner.

### Monitoring and Logging

- [ ] Confirm CloudWatch Agent or another monitoring agent is configured.
- [ ] Confirm disk usage alerts exist.
- [ ] Confirm service failure alerts exist.
- [ ] Confirm application logs are retained.
- [ ] Confirm CloudTrail is enabled at the AWS account level.

### Web / Application

- [ ] Confirm HTTPS configuration.
- [ ] Confirm certificate renewal process.
- [ ] Confirm web server configuration backup.
- [ ] Confirm application deployment process.
- [ ] Confirm environment variables and secrets handling.

### Handover

- [ ] Confirm server purpose.
- [ ] Confirm administrator contacts.
- [ ] Confirm recovery procedure.
- [ ] Confirm important file paths.
- [ ] Confirm scheduled jobs.
- [ ] Confirm known risks and next actions.

EOF
}

write_header
write_summary_findings

section "System Information"
run_cmd "Hostname" hostnamectl
run_cmd "OS Release" cat /etc/os-release
run_cmd "Kernel" uname -a
run_cmd "Uptime" uptime
run_cmd "Current User and Groups" id
run_cmd "System Time" timedatectl

section "AWS / EC2 Metadata"
run_shell "EC2 Metadata Token Test" "if command -v curl >/dev/null 2>&1; then curl -sS --connect-timeout 2 -X PUT 'http://169.254.169.254/latest/api/token' -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' | sed 's/.*/IMDSv2 token endpoint responded/' ; else echo 'curl not found'; fi"
run_shell "EC2 Instance Identity Document" "if command -v curl >/dev/null 2>&1; then TOKEN=\$(curl -sS --connect-timeout 2 -X PUT 'http://169.254.169.254/latest/api/token' -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' 2>/dev/null || true); if [ -n \"\$TOKEN\" ]; then curl -sS --connect-timeout 2 -H \"X-aws-ec2-metadata-token: \$TOKEN\" 'http://169.254.169.254/latest/dynamic/instance-identity/document'; else echo 'Could not get IMDSv2 token or not running on EC2'; fi; else echo 'curl not found'; fi"

section "Disk and Filesystem"
run_cmd "Disk Usage" df -hT
run_cmd "Block Devices" lsblk -f
run_cmd "Mounts" findmnt
run_shell "Large Directories Under Root" "du -xhd1 / 2>/dev/null | sort -h | tail -20"

section "Memory and CPU"
run_cmd "Memory Usage" free -h
run_cmd "CPU Information" lscpu
run_shell "Top Memory Processes" "ps aux --sort=-%mem | head -15"
run_shell "Top CPU Processes" "ps aux --sort=-%cpu | head -15"

section "Package Updates"
run_shell "APT Update Simulation Status" "if command -v apt >/dev/null 2>&1; then apt list --upgradable 2>/dev/null | sed -n '1,80p'; else echo 'apt not found'; fi"
run_shell "Unattended Upgrades Package" "dpkg -l | grep -E '^ii\\s+unattended-upgrades' || echo 'unattended-upgrades not installed or not found'"
run_shell "Reboot Required Check" "if [ -f /var/run/reboot-required ]; then cat /var/run/reboot-required; else echo 'No reboot-required file found'; fi"

section "Firewall and Network Exposure"
run_shell "UFW Status" "if command -v ufw >/dev/null 2>&1; then ufw status verbose; else echo 'ufw not found'; fi"
run_shell "Listening TCP/UDP Ports" "if command -v ss >/dev/null 2>&1; then ss -tulpen; elif command -v netstat >/dev/null 2>&1; then netstat -tulpen; else echo 'ss and netstat not found'; fi"
run_shell "IP Addresses" "ip addr show"
run_shell "Routing Table" "ip route show"

section "SSH Configuration"
run_shell "SSH Service Status" "systemctl status ssh --no-pager 2>/dev/null || systemctl status sshd --no-pager 2>/dev/null || echo 'ssh/sshd service not found'"
run_shell "Effective SSH Security-Related Settings" "if [ -f /etc/ssh/sshd_config ]; then grep -Ei '^(PermitRootLogin|PasswordAuthentication|PubkeyAuthentication|ChallengeResponseAuthentication|KbdInteractiveAuthentication|AllowUsers|AllowGroups|DenyUsers|DenyGroups|Port|ListenAddress)' /etc/ssh/sshd_config || echo 'No matching explicit settings found in /etc/ssh/sshd_config'; else echo '/etc/ssh/sshd_config not found'; fi"
run_shell "Authorized Keys Files" "find /home /root -maxdepth 3 -name authorized_keys -type f -print 2>/dev/null"

section "Users and Privilege"
run_shell "Users With Login Shells" "awk -F: '($7 !~ /(nologin|false)$/) {print $1 \":\" $6 \":\" $7}' /etc/passwd"
run_shell "Sudo Group Members" "getent group sudo || true"
run_shell "Recent Logins" "last -n 20"
run_shell "Failed Login Summary" "lastb -n 20 2>/dev/null || echo 'lastb not available or permission denied'"

section "Systemd Services"
run_cmd "Failed Services" systemctl --failed --no-pager
run_shell "Enabled Services" "systemctl list-unit-files --type=service --state=enabled --no-pager | sed -n '1,120p'"
run_shell "Timers" "systemctl list-timers --all --no-pager"

section "Docker"
run_shell "Docker Version" "if command -v docker >/dev/null 2>&1; then docker version; else echo 'docker not found'; fi"
run_shell "Docker Service Status" "systemctl status docker --no-pager 2>/dev/null || echo 'docker service not found'"
run_shell "Docker Containers" "if command -v docker >/dev/null 2>&1; then docker ps -a; else echo 'docker not found'; fi"
run_shell "Docker Images" "if command -v docker >/dev/null 2>&1; then docker images; else echo 'docker not found'; fi"
run_shell "Docker Disk Usage" "if command -v docker >/dev/null 2>&1; then docker system df; else echo 'docker not found'; fi"

section "Web Server and TLS-Related Services"
run_shell "Nginx Status" "systemctl status nginx --no-pager 2>/dev/null || echo 'nginx service not found'"
run_shell "Apache Status" "systemctl status apache2 --no-pager 2>/dev/null || echo 'apache2 service not found'"
run_shell "Certbot Status" "if command -v certbot >/dev/null 2>&1; then certbot certificates; else echo 'certbot not found'; fi"

section "Backup Readiness"
run_shell "Common Backup Directories" "for d in /backup /backups /var/backups /opt/backups /srv/backups /home/ubuntu/backups; do if [ -e \"\$d\" ]; then echo \"FOUND: \$d\"; ls -lah \"\$d\" 2>/dev/null | sed -n '1,40p'; else echo \"MISSING: \$d\"; fi; done"
run_shell "Cron Jobs" "for f in /etc/crontab /etc/cron.d/*; do [ -e \"\$f\" ] && echo \"--- \$f ---\" && sed -n '1,120p' \"\$f\"; done"
run_shell "User Crontabs" "for u in \$(cut -f1 -d: /etc/passwd); do crontab -l -u \"\$u\" 2>/dev/null | sed \"s/^/[user:\$u] /\"; done"

section "Monitoring and Security Agents"
run_shell "CloudWatch Agent" "systemctl status amazon-cloudwatch-agent --no-pager 2>/dev/null || echo 'amazon-cloudwatch-agent service not found'"
run_shell "AWS SSM Agent" "systemctl status amazon-ssm-agent --no-pager 2>/dev/null || echo 'amazon-ssm-agent service not found'"
run_shell "Fail2ban" "systemctl status fail2ban --no-pager 2>/dev/null || echo 'fail2ban service not found'"
run_shell "Auditd" "systemctl status auditd --no-pager 2>/dev/null || echo 'auditd service not found'"

section "Log Overview"
run_shell "Recent System Errors" "journalctl -p err -n 80 --no-pager 2>/dev/null || echo 'journalctl error access failed'"
run_shell "Auth Log Tail" "if [ -f /var/log/auth.log ]; then tail -80 /var/log/auth.log; else echo '/var/log/auth.log not found'; fi"

section "Recommended Next Review"
write_manual_review_notes

echo "Report created: ${REPORT_FILE}"